//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinformTest.RemoteServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteServer.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getHunanGps_pxjl", ReplyAction="http://tempuri.org/IService1/getHunanGps_pxjlResponse")]
        string getHunanGps_pxjl(string username, string password, string pxjl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveHunanGps_pxjl", ReplyAction="http://tempuri.org/IService1/SaveHunanGps_pxjlResponse")]
        string SaveHunanGps_pxjl(string username, string password, string[] pxjls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveHunanGps_pxjlByStr", ReplyAction="http://tempuri.org/IService1/SaveHunanGps_pxjlByStrResponse")]
        string SaveHunanGps_pxjlByStr(string username, string password, string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WinformTest.RemoteServer.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WinformTest.RemoteServer.IService1>, WinformTest.RemoteServer.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getHunanGps_pxjl(string username, string password, string pxjl) {
            return base.Channel.getHunanGps_pxjl(username, password, pxjl);
        }
        
        public string SaveHunanGps_pxjl(string username, string password, string[] pxjls) {
            return base.Channel.SaveHunanGps_pxjl(username, password, pxjls);
        }
        
        public string SaveHunanGps_pxjlByStr(string username, string password, string str) {
            return base.Channel.SaveHunanGps_pxjlByStr(username, password, str);
        }
    }
}
